[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "rompy_ccam"
description = "Rompy CCAM Config package."
readme = "README.rst"
authors = [
  {name = "Rompy Developers", email = "developers@rompy.com"}
]
maintainers = [
  {name = "Rompy Developers", email = "developers@rompy.com"}
]
classifiers = [

]
license = {text = "Apache Software License 2.0"}
dependencies = [
  "rompy",
  "typer",
  "f90nml"
]

dynamic = ["version"]

[project.optional-dependencies]
dev = [
    "coverage",
    "mypy",
    "pytest",
    "ruff",
    "black",
    "requests"
]
docs = [
    "mkdocs<2.0",
    "mkdocs-material",
    "mkdocstrings[python]",
    "pymdown-extensions",
]

[project.scripts]
rompy_ccam = "rompy_ccam.cli:app"

[project.entry-points."rompy.config"]
ccam = "rompy_ccam.config:CCAMConfig"
null = "rompy_ccam.rompy_ccam:NullConfig"
composed = "rompy_ccam.rompy_ccam:ComposedConfig"
default = "rompy_ccam.default_workflow:CCAMDefaultWorkflow"
sequence = "rompy_ccam.workflow_sequence:CCAMWorkflowSequence"
globpea = "rompy_ccam.ccam.globpea:GlobpeaConfig"
terread = "rompy_ccam.ccam.terread:TerreadConfig"
igbpveg = "rompy_ccam.ccam.igbpveg:IgbpvegConfig"
cdfvidar = "rompy_ccam.ccam.cdfvidar:CdfvidarConfig"
casafield = "rompy_ccam.ccam.casafield:CasafieldConfig"
ocnbath = "rompy_ccam.ccam.ocnbath:OcnbathConfig"
aeroemiss = "rompy_ccam.ccam.aeroemiss:AeroemissConfig"

[project.entry-points."rompy.source"]
# Register here any new source. For example:
# ccam_source_type = "rompy_ccam.source:CCAMSource"

[project.urls]
bugs = "https://github.com/rom-py/rompy_ccam/issues"
changelog = "https://github.com/rom-py/rompy_ccam/blob/master/changelog.md"
homepage = "https://github.com/rom-py/rompy_ccam"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
"*" = ["*.*"]

[tool.setuptools.dynamic]
version = {attr = "rompy_ccam.__version__"}
